# paths are relative to auto_annotations

greedy_gpt4 : # gpt-4-0314_pairwise_vH_b5_chatml-prompt
  prompt_template:
    with_inputs: "greedy_gpt4/chatml_b5_with_inputs.txt"
    without_inputs: "greedy_gpt4/chatml_b5_without_inputs.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4-0314"
    max_tokens: 250
    temperature: 0
  completion_parser_kwargs:
    outputs_to_match:
      1: '(?:^|\n) ?Output \(a\)'
      2: '(?:^|\n) ?Output \(b\)'
  batch_size: 5
